FROM ghcr.io/actions/actions-runner:2.304.0
# for latest release, see https://github.com/actions/runner/releases

USER root

RUN apt-get update && \
    apt-get install -y git jq unzip curl && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

COPY github-actions-runner/entrypoint.sh ./entrypoint.sh

RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
